CREATE TABLE `marli_songs` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`song_id` VARCHAR(255) NOT NULL,
	`song_name` TEXT NOT NULL
);

INSERT INTO `marli_songs` (song_id, song_name) VALUES
('abra_seus_olhos', 'Abra Seus Olhos'),
('alem_do_arco_iris', 'Além Do Arco Íris'),
('amor_de_urubu', 'Amor De Urubu'),
('armando_um_barraco', 'Armando Um Barraco'),
('bertulina', 'Bertulina'),
('bruxas_e_viuvas', 'Bruxas E Viúvas'),
('cachaca', 'Cachaça'),
('cemiterio', 'Cemitério'),
('eu_gosto_de_louvar', 'Eu Gosto De Louvar'),
('eu_vou_chopar_ela', 'Eu Vou Chopar Ela'),
('galactica', 'Galáctica'),
('garota_crente', 'Garota Crente'),
('hoje_nao_tem_manicoba', 'Hoje Não Tem Maniçoba'),
('ladra_de_namorados', 'Ladra De Namorados'),
('linha_direta', 'Linha Direta'),
('macumba_pirata', 'Macumba Pirata'),
('mais_um_presente_no_saco', 'Mais Um Presente No Saco'),
('menina_capitolina', 'Menina Capitolina'),
('na_sua_alma', 'Na Sua Alma'),
('o_amor_esta_no_ar', 'O Amor Está No Ar'),
('o_olho_do_tarado', 'O Olho Do Tarado'),
('odisseia_clitoriana', 'Odisséia Clitoriana'),
('pirulito', 'Pirulito'),
('planalto_central', 'Planalto Central'),
('purpurina', 'Purpurina'),
('rainha_das_trevas', 'Rainha Das Trevas'),
('recarga', 'Recarga'),
('sagrada', 'Sagrada'),
('sangue', 'Sangue'),
('suave_peste_negra', 'Suave Peste Negra'),
('uma_garota_do_cacete', 'Uma Garota Do Cacete'),
('vai_pro_inferno', 'Vai Pro Inferno'),
('virgem_brasileira', 'Virgem Brasileira');